export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    mfa: {
      setup: '/auth/mfa/setup',
      verify: '/auth/mfa/verify',
      disable: '/auth/mfa/disable',
    },
    sessions: '/auth/sessions',
    profile: '/auth/profile',
  },
  users: {
    list: '/users',
    get: (id: string) => `/users/${id}`,
    create: '/users',
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
  },
  teams: {
    list: '/teams',
    get: (id: string) => `/teams/${id}`,
    create: '/teams',
    update: (id: string) => `/teams/${id}`,
    delete: (id: string) => `/teams/${id}`,
    members: (id: string) => `/teams/${id}/members`,
  },
  tenants: {
    current: '/tenants/current',
    list: '/tenants',
    update: (id: string) => `/tenants/${id}`,
    branding: (id: string) => `/tenants/${id}/branding`,
    settings: (id: string) => `/tenants/${id}/settings`,
  },
  billing: {
    plans: '/billing/plans',
    subscription: '/billing/subscription',
    invoices: '/billing/invoices',
    paymentMethods: '/billing/payment-methods',
    usage: '/billing/usage',
  },
  analytics: {
    overview: '/analytics/overview',
    users: '/analytics/users',
    revenue: '/analytics/revenue',
    performance: '/analytics/performance',
    export: '/analytics/export',
  },
  notifications: {
    list: '/notifications',
    read: (id: string) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
    preferences: '/notifications/preferences',
  },
  audit: {
    list: '/audit',
    get: (id: string) => `/audit/${id}`,
    export: '/audit/export',
  },
  plugins: {
    list: '/plugins',
    get: (id: string) => `/plugins/${id}`,
    install: (id: string) => `/plugins/${id}/install`,
    uninstall: (id: string) => `/plugins/${id}/uninstall`,
    configure: (id: string) => `/plugins/${id}/config`,
    registry: '/plugins/registry',
  },
  settings: {
    general: '/settings/general',
    security: '/settings/security',
    notifications: '/settings/notifications',
    integrations: '/settings/integrations',
  },
  featureFlags: {
    list: '/feature-flags',
    check: (key: string) => `/feature-flags/${key}`,
  },
} as const;
